name: Ejecución Diaria TRM

on:
  schedule:
    # Se ejecuta todos los días a las 11:00 UTC (6:00 AM Colombia aprox)
    - cron: '0 11 * * *'
  workflow_dispatch: # Permite que haya un botón para ejecutarlo manualmente

jobs:
  etl-job:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install pandas sodapy sqlalchemy psycopg2-binary python-dotenv

      - name: Ejecutar Pipeline ETL
        env:
          DATABASE_NEON: ${{ secrets.DATABASE_NEON }}
          API_DOMAIN: ${{ secrets.API_DOMAIN }}
          API_DATASET_ID: ${{ secrets.API_DATASET_ID }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          LIMIT: ${{ secrets.LIMIT }}
        run: python Trm_Diaria.py